### PR TITLE
Changes to save async instance port and pass it along with onConnect

### PR DESCRIPTION
**Pull request by akhildabral**
Changes to save async instance port and pass it along with onConnect and onDisconnect method.

### CODE REVIEW

**Comment by blackjack** [comment]
Can you describe your use case? The library doesn't support multiple connections to Redis server, so why do you need port number passed in callback? You can just store port number in any other place or add getPort() method to BooRedis(A)Sync class.

**Comment by akhildabral** [comment]
The motive of storing port number and passing it along with onConnect and onDisconnect callbacks is to handle multiple connections. I am trying to connect to multiple instances of redis in my project. 
Because callback do no have port ,i am not able to identify the instance.
This change helps in handling that case.

**Comment by akhildabral** [comment]
I have done further changes to pass the port along with onRedisMessage function. Also added overloaded virtual methods to support backward compatibility.

By these changes used can manage multiple connection by its own and the library can let them know the correct instance.

**Comment by akhildabral** [comment]
@blackjack can you please merge this pull.

**Comment by blackjack** [comment]
I'm sorry, but I don't find passing port in every callback. I mean, there are tons of ways to implement it on application level without affecting library semantics, moreover, it will break API. 

One example I can suggest you is something like this:
```
class RedisAsyncWithPort: public BooRedisAsync {
  int current_port = 0;

public:
  virtual void onRedisMessageWithPort(const RedisMessage& msg, int port) = 0;

  virtual void onRedisMessage(const RedisMessage& msg) final override {
    onRedisMessageWithPort(msg, current_port);
  };

  void connect(const char* address, int port, int timeout_msec) {
    current_port = port;
    BooRedisAsync::connect(address, port, timeout_msec);
  }
};


class RedisWorker: public RedisAsyncWithPort {
public:
    void onRedisMessageWithPort(const RedisMessage& msg, int port) override {}
};
```

**Comment by akhildabral** [comment]
@blackjack I understand your point of not changing the Library semantics. But if you look closely i have not introduced any new method/callback with ports, instead its the same method over loaded. 
So the implementer can override the abstract method onConnect as

`onConnect();`
or
`onConnect(int port);`

So as you have mentioned in your example there is no method as onRedisMessageWithPort

```
class RedisAsyncWithPort: public BooRedisAsync {
  int current_port = 0;

public:
  virtual void onRedisMessage(const RedisMessage& msg, int port) = 0;

  virtual void onRedisMessage(const RedisMessage& msg) final override {
    onRedisMessage(msg, current_port);
  };

  void connect(const char* address, int port, int timeout_msec) {
    current_port = port;
    BooRedisAsync::connect(address, port, timeout_msec);
  }
};
```

Also if you see any issue in passing port with every onRedisMessage call then that can removed 

Only thing which is required port for handling multiple instance externally is onConnect and onDisconnect.
To understand which connection is connected and precisely know which one got disconnected.

**Pull request closed without merging**
